# Generated by Django 3.2.3 on 2021-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sImg', models.ImageField(blank=True, null=True, upload_to='images/sreduced/')),
                ('xsImg', models.ImageField(blank=True, null=True, upload_to='images/xsreduced/')),
                ('xxsImg', models.ImageField(blank=True, null=True, upload_to='images/xxsreduced/')),
            ],
        ),
    ]
